services:
  - type: web
    name: notesapp-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ADMIN_USERNAME
        value: sarthakhello
      - key: JWT_SECRET
        value: mySecretJwtKey123456789
      - key: SPRING_PROFILES_ACTIVE
        value: production